# Generated by Django 5.0.3 on 2024-03-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=3, null=True)),
                ('img', models.ImageField(blank=True, upload_to='static/members/')),
                ('std_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('comment', models.TextField(blank=True, max_length=120)),
                ('insta_link', models.URLField(blank=True)),
                ('git_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('tf', models.BooleanField(default=False)),
            ],
        ),
    ]
