# Generated by Django 5.0.3 on 2024-04-19 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild_id", models.CharField(max_length=100, unique=True)),
                ("guild_quiz_list", models.JSONField(default=list)),
                ("ctf_id", models.CharField(max_length=100)),
                ("guild_name", models.CharField(max_length=100)),
                ("guild_birth", models.DateField()),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guild",
                        to="auth.group",
                    ),
                ),
            ],
        ),
    ]
