# Generated by Django 5.0.3 on 2024-05-17 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild_Wargame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_description', models.TextField()),
                ('quiz_flag', models.CharField(max_length=100)),
                ('quiz_title', models.CharField(max_length=100)),
                ('quiz_level', models.CharField(choices=[('high', 'High'), ('intermediate', 'Intermediate'), ('beginner', 'Beginner')], max_length=20)),
                ('quiz_type', models.CharField(choices=[('web', 'Web'), ('system', 'System Hacking'), ('crypto', 'Crypto'), ('forensics', 'Forensics'), ('reversing', 'Reverse Engineering'), ('misc', 'Miscellaneous')], max_length=20)),
                ('quiz_file', models.FileField(blank=True, null=True, upload_to='wargame_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_name', models.CharField(max_length=100, unique=True)),
                ('guild', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guild', to='auth.group')),
            ],
        ),
    ]
