# Generated by Django 5.0.3 on 2024-04-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wargame',
            name='quiz_file',
            field=models.FileField(null=True, upload_to='wargame_files/'),
        ),
        migrations.AlterField(
            model_name='wargame',
            name='quiz_title',
            field=models.CharField(max_length=100),
        ),
    ]
