# Generated by Django 5.0.3 on 2024-04-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargame', '0002_wargame_quiz_file_alter_wargame_quiz_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wargame',
            name='quiz_level',
            field=models.CharField(choices=[('high', 'High'), ('intermediate', 'Intermediate'), ('beginner', 'beginner')], max_length=20),
        ),
    ]
